name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Dancing Tiled Demo Web App
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./demo
      - run: flutter build web
        working-directory: ./demo
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: github-pages
          path: ./demo/build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
